### ISSUE TITLE
How to select and delete one point? 

### ISSUE THREAD

**Issue by You-zeyi** [seqsense/pcdeditor#144]
Dear developers:
I had been playing with pcdeditor on your website for a while. However I cant figure out how to select only one point and then delete it. It seems like I have to select three or four points and then delete the whole cube defined by these points. It is not easy to select exact points that I want to delete in this way.

**Comment by at-wat** [comment]
You can select single point by following commands:
1. enter `segmentation_param 0.001 0.002` to the command box
  (This command sets point segmentation parameter to select neighbor points within 1mm, which approximates to select single point)
3. Alt+LeftClick to select a point

**Comment by You-zeyi** [comment]
> You can select single point by following commands:
> 
>     1. enter `segmentation_param 0.001 0.002` to the command box
>        (This command sets point segmentation parameter to select neighbor points within 1mm, which approximates to select single point)
> 
>     2. Alt+LeftClick to select a point

Thanks, it worked
